name: health_app
description: "A new Flutter project."
publish_to: 'none'  # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  hive: any
  hive_flutter: any
  csv: any
  path_provider: any
  cupertino_icons: any
  flutter_cache_manager: ^3.3.0
  url_launcher: ^6.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/quotes.csv  # Quotes CSV
    - assets/recipes.csv  # Recipes CSV
    - assets/images/1001.png  # Recipe images
    - assets/images/1002.png
    - assets/images/1003.png
    - assets/images/1004.png
    - assets/images/1005.png
    - assets/images/1006.png
    - assets/images/1007.png
    - assets/images/1008.png
    - assets/images/1009.png
    - assets/images/1010.png
